import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className + ' w-full bg-red-100'}>
        <div className="__next">
    

       

              <main className="w-full" id="main">
                <div className="w-full" id="main-content">
                  {children}
                </div>
              </main>
  

 
        </div>
      </body>
    </html>
  );
}
